// ABOUTME: The dependency bundle and registration surface every tool closes over, and the browser-pool
// ABOUTME: contract that keeps one attached CDP page per Steel session so refs survive across calls.
import { createHash, randomUUID } from 'node:crypto';
import type { McpServer, RequestStateCodec } from '@modelcontextprotocol/server';
import type { Tracer } from '@opentelemetry/api';
import type { ArtifactPublisher } from './artifacts.js';
import type { SteelConfig } from './config.js';
import { buildCdpUrl } from './config.js';
import { SteelToolError } from './errors.js';
import type { HandoffState } from './mrtr.js';
import { BrowserPage } from './page.js';
import type { RateLimiter } from './rate-limit.js';
import type { HandleRegistry } from './registry.js';
import type { SessionPlanState } from './session-plan.js';
import { resolveSettleBudgets } from './settle.js';
import { CdpConnection, type CdpSession } from './steel/cdp.js';
import type { SteelApi } from './steel/types.js';
import { resolveTracer, withCdpSpan } from './telemetry.js';

/**
 * The registration surface handed to the tool modules.
 *
 * Narrower than `McpServer` on purpose: because a tool can only register itself through it, the
 * hosted entry can hand over a wrapper that charges the request budget before any handler runs,
 * and a tool added later is metered without anyone having to remember to ask for it. `server` is
 * passed through unwrapped so a tool can read connect-time client capabilities.
 */
export type ToolHost = Pick<McpServer, 'registerTool' | 'server'>;

/** Hands out the attached page for a Steel session, creating the CDP connection on first use. */
export interface SessionPool {
    page(steelSessionId: string, signal?: AbortSignal): Promise<BrowserPage>;
    close(steelSessionId: string): Promise<void>;
    closeAll(): Promise<void>;
}

/** Everything the tool layer needs. Held at module scope and closed over by the server factory. */
export interface ServerDeps {
    config: SteelConfig;
    api: SteelApi;
    registry: HandleRegistry;
    pool: SessionPool;
    /**
     * Seals and verifies the multi-round-trip state a human-in-the-loop handoff round-trips.
     *
     * Injected rather than derived per request because every replica that might receive the retry
     * has to hold the same key; a per-instance codec would reject its own flow's second round.
     */
    handoffState: RequestStateCodec<HandoffState>;
    /** Signs planner settings for this principal; verified manually by session creation. */
    sessionPlanState: RequestStateCodec<SessionPlanState>;
    /** The principal for this request's own credential; handles are re-authorised against it. */
    principal: string;
    /**
     * Cost-weighted admission control for this principal.
     *
     * Absent on stdio: one process serves one credential there, so there is no neighbour to
     * protect and a budget would only stop the single tenant from using what it already pays for.
     */
    limiter?: RateLimiter | undefined;
    /**
     * Multiplier applied to settle budgets, because Steel sessions reach the internet through
     * Steel's fleet and often a proxy, so the localhost-tuned constants are too tight.
     */
    settleMultiplier: number;
    now(): Date;
    /** Downloads hosted screenshots so tool results can embed them for chat UIs. */
    artifactFetch?: typeof globalThis.fetch | undefined;
    /** Test seam for OpenRouter Decisions requests. */
    jevFetch?: typeof globalThis.fetch | undefined;
    /** Briefly hosts generated bytes behind a signed URL for downstream upload tools. */
    artifacts?: ArtifactPublisher | undefined;
    /** Test seam for the one managed-credential injection grace; production uses an abort-aware 2s wait. */
    credentialGrace?: ((signal?: AbortSignal) => Promise<void>) | undefined;
    /** Overridable so tests get deterministic Steel session ids. */
    newSessionId?: (() => string) | undefined;
    /**
     * Tracer the tool layer opens its per-call spans on. Left unset, the globally registered
     * OpenTelemetry tracer is used, which is a no-op until an entrypoint configures an exporter.
     */
    tracer?: Tracer | undefined;
}

/** Mints the session UUID before the create call, closing the create-then-crash gap. */
export function mintSteelSessionId(deps: ServerDeps): string {
    return (deps.newSessionId ?? randomUUID)();
}

/** Stable, non-secret UUID used only to select this principal's self-hosted Chrome profile. */
export function defaultSelfHostedProfileId(principal: string): string {
    const bytes = createHash('sha256').update('tlon:self-hosted-browser-profile:v1\0').update(principal).digest();
    bytes[6] = (bytes[6]! & 0x0f) | 0x50;
    bytes[8] = (bytes[8]! & 0x3f) | 0x80;
    const hex = bytes.subarray(0, 16).toString('hex');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** The connection behaviour the pool depends on, so tests can supply one without a socket. */
export interface PooledConnection {
    attachToPage(): Promise<CdpSession>;
    close(): Promise<void>;
    readonly isClosed: boolean;
}

/** Opens a CDP connection to a URL. Injected so the pool's lifecycle is testable on its own. */
export type CdpConnector = (url: string, signal?: AbortSignal) => Promise<PooledConnection>;

interface PoolEntry {
    connection: PooledConnection;
    page: BrowserPage;
}

/** How many times `page` will evict a dead connection and reconnect before giving up. */
const MAX_RECONNECT_ATTEMPTS = 3;

/**
 * Opens one CDP connection per Steel session and keeps the attached page for later calls.
 *
 * The map holds the in-flight connect promise rather than the finished entry, so concurrent
 * callers share one connection instead of racing to open several — a loser's socket would leak
 * for the session's whole life, and ref state would split across two `PageState` instances.
 */
export class CdpSessionPool implements SessionPool {
    private readonly entries = new Map<string, Promise<PoolEntry>>();

    constructor(
        private readonly config: SteelConfig,
        private readonly settleMultiplier: number,
        private readonly connect: CdpConnector = CdpConnection.connect,
        private readonly tracer: Tracer = resolveTracer()
    ) {}

    private async open(steelSessionId: string, signal?: AbortSignal): Promise<PoolEntry> {
        return withCdpSpan(this.tracer, 'connect', steelSessionId, () => this.openConnection(steelSessionId, signal));
    }

    private async openConnection(steelSessionId: string, signal?: AbortSignal): Promise<PoolEntry> {
        const connection = await this.connect(buildCdpUrl(this.config, steelSessionId), signal);
        try {
            const session = await connection.attachToPage();
            const page = await BrowserPage.attach(session, { budgets: resolveSettleBudgets(this.settleMultiplier) });
            return { connection, page };
        } catch (error) {
            // The socket is open but unusable; close it here or nothing ever will.
            await connection.close().catch(() => undefined);
            throw error;
        }
    }

    async page(steelSessionId: string, signal?: AbortSignal): Promise<BrowserPage> {
        for (let attempt = 0; attempt < MAX_RECONNECT_ATTEMPTS; attempt++) {
            const existing = this.entries.get(steelSessionId);

            if (!existing) {
                // No await between the miss and the set, so two callers cannot both start a connect.
                const pending = this.open(steelSessionId, signal);
                this.entries.set(steelSessionId, pending);
                try {
                    return (await pending).page;
                } catch (error) {
                    // A failed connect must not be cached, or the session is unusable for good.
                    if (this.entries.get(steelSessionId) === pending) this.entries.delete(steelSessionId);
                    throw error;
                }
            }

            const entry = await existing.catch(() => undefined);
            if (entry && !entry.connection.isClosed) return entry.page;

            // Only the caller that still sees this promise evicts it; the others re-read the map,
            // so a dropped socket costs one reconnect rather than one per waiting caller.
            if (this.entries.get(steelSessionId) === existing) {
                this.entries.delete(steelSessionId);
                await entry?.connection.close().catch(() => undefined);
            }
        }

        throw new SteelToolError(
            'The browser connection for this session keeps dropping. Release the session with ' +
                'browser_session_release and create a new one.',
            { code: 'session_expired', details: { steelSessionId } }
        );
    }

    async close(steelSessionId: string): Promise<void> {
        const pending = this.entries.get(steelSessionId);
        if (!pending) return;
        this.entries.delete(steelSessionId);
        // Awaiting the in-flight connect is what stops a socket that opens after this call leaking.
        const entry = await pending.catch(() => undefined);
        await entry?.connection.close().catch(() => undefined);
    }

    async closeAll(): Promise<void> {
        await Promise.all([...this.entries.keys()].map(id => this.close(id)));
    }
}
